"""Auto-generated by app.py scene editor.

Do not edit by hand unless you know what you're doing.
Module name: scene_editor_output
"""
import math
import numpy as np
from src.base import BaseScene, Color
from src.vector3d import Vector3D
from src.camera import Camera
from src.light import AreaLight
from src.shapes import Ball, Cube, PlaneUV, ObjectTransform, Translate, Cilinder
from src.materials import SimpleMaterialWithShadows, CheckerboardMaterial, ReflectiveMaterial

def _m(m):
    return np.array(m, dtype=float)

class Scene(BaseScene):
    def __init__(self):
        super().__init__('Editor Scene')
        self.background = Color(0.7, 0.8, 0.95)
        self.ambient_light = Color(0.1, 0.1, 0.1)
        self.max_depth = 4
        self.camera = Camera(
            eye=Vector3D(12, 12, 4),
            look_at=Vector3D(0, 0, 2.5),
            up=Vector3D(0, 0, 1),
            fov=45,
            img_width=500,
            img_height=500,
        )
        self.lights = [AreaLight(
            position=Vector3D(10, 5, 15),
            look_at=Vector3D(0, 0, 0),
            up=Vector3D(1, 1, 1),
            width=4,
            height=4,
            color=Color(0.8, 0.6, 0.6),
            intensity=1.7)]

        _mat_ground = CheckerboardMaterial(1, 0.9, 1)
        _shape_ground = PlaneUV(point=Vector3D(0, 0, 0), normal=Vector3D(0, 0, 1), forward_direction=Vector3D(1, 0, 0))
        self.add(_shape_ground, _mat_ground)

        _mat_ball1 = SimpleMaterialWithShadows(0.12, 0.9, Color(0.2, 0.85, 0.2), 0.15, Color(1,1,1), 32)
        _shape_ball1 = Ball(center=Vector3D(0,0,0), radius=0.8)
        _shape_ball1 = ObjectTransform(_shape_ball1, _m([[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]))
        _shape_ball1 = Translate(_shape_ball1, Vector3D(-2.5, 0, 0.8))
        self.add(_shape_ball1, _mat_ball1)

        _mat_cube1 = ReflectiveMaterial(0.0, 0.0, Color(0,0,0), 0.0, Color(0,0,0), reflection_coefficient=0.8)
        _shape_cube1 = Cube(size=1)
        _shape_cube1 = ObjectTransform(_shape_cube1, _m([[1.299038105676658, -0.7499999999999999, 0.0], [0.7499999999999999, 1.299038105676658, 0.0], [0.0, 0.0, 1.5]]))
        _shape_cube1 = Translate(_shape_cube1, Vector3D(2, 0, 1))
        self.add(_shape_cube1, _mat_cube1)

